linters-settings:
  depguard:
    rules:
      main:
        list-mode: strict
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - github.com/fatih/color
          - github.com/gin-gonic/gin
          - github.com/spacecafe
      tests:
        list-mode: strict
        files:
          - "$test"
        allow:
          - $gostd
          - github.com/gin-gonic/gin
          - github.com/spacecafe
          - github.com/stretchr/testify
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
  gocyclo:
    min-complexity: 10
  gofmt:
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
      - pattern: 'a[b:len(a)]'
        replacement: 'a[b:]'

linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exportloopref
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - funlen