---
name: go-modules

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  go-modules:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Collect go modules
        id: set-matrix
        run: go list -m -json
...
