---
name: go-test

'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  list-modules:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Collect go modules
        id: set-matrix
        run: echo "matrix="$(go list -m -json | jq -cs '[.[].Dir]')"" >> $GITHUB_OUTPUT
  govulncheck:
    needs: list-modules
    runs-on: ubuntu-latest
    strategy:
      matrix:
        manifest: ${{ fromJson(needs.list-modules.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-package: ${{ matrix }}

  golangci:
    needs: list-modules
    runs-on: ubuntu-latest
    strategy:
      matrix:
        manifest: ${{ fromJson(needs.list-modules.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: "${{ matrix }}"

  staticcheck:
    needs: list-modules
    runs-on: ubuntu-latest
    strategy:
      matrix:
        manifest: ${{ fromJson(needs.list-modules.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          working-directory: ${{ matrix }}

  go-test:
    needs: list-modules
    runs-on: ubuntu-latest
    strategy:
      matrix:
        manifest: ${{ fromJson(needs.list-modules.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Test
        run: go test -v "${{ matrix }}"
...
