---
name: gosec

'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  gosec:
    needs: go-modules
    runs-on: ubuntu-latest
    strategy:
      matrix:
        manifest: ${{ fromJson(needs.go-modules.outputs.matrix) }}
    env:
      GO111MODULE: true
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: '${{ matrix.Dir }}'
---
