name: govulncheck

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Run govulncheck
      uses: golang/govulncheck-action@v1
      with:
        go-package: ./...
